# Image PHP officielle avec FPM
FROM php:8.3-fpm

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    libsodium-dev \
    git \
    unzip \
    libicu-dev \
    libonig-dev \
    libpq-dev \
    && docker-php-ext-install sodium intl pdo pdo_mysql mbstring opcache \
    && rm -rf /var/lib/apt/lists/*

# Installer Composer globalement
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copier configuration OPcache
COPY conf.d/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

# Définir le répertoire de travail
WORKDIR /var/www/symfony