# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # 🔹 Authentification par JWT pour l’API
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider

            json_login:
                check_path: /api/login_check
                username_path: email # ici on utilise ton email comme identifiant
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            provider: app_user_provider
            lazy: true
            custom_authenticators:
                - App\Security\AppAuthentificatorAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS } # point de login JWT
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/invalidate, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
