services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Toutes les classes dans src/ sont des services
    App\:
        resource: "../src/*"
        exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

    # Listener JWT personnalisé
    App\EventListener\AuthenticationSuccessListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_success,
                  method: onAuthenticationSuccessResponse,
              }
